### ISSUE TITLE
Not a genuine representation of a user's collection

### ISSUE THREAD

**Issue by purplehat7** [twaddington/python-rdio-export#5]
The exporter outputs the albums of all the songs in a user's collection, as if the user's collection was comprised entirely of complete albums. A list of the tracks in a user's Collection would be more useful/accurate.

**Comment by twaddington** [comment]
Hey, sorry for the delayed replay, GitHub was apparently not sending me notifications on this repository.

I appreciate the feedback. In my case I tend to orient myself around albums instead of individual tracks. For example, if I wanted to rebuild my collection from scratch I'd want to know what albums I would need to buy or download in order to do so.

I realize for some people who have a lot of single tracks it may not be ideal. I might consider adding a `--flat` option in the future that outputs tracks individually one on each line.
